# vrijeme transfera izmedju autobuske i zeljeznicke stanice
DEFAULT_TRANSFER_TIME = 5
# broj dodatnih ruta koje se prikazuju
DEFAULT_MAX_RESULTS = 5
# putanja do json fajla sa podacima o transportu
TRANSPORT_DATA_PATH = src/main/resources/transport_data.json
